#!/usr/bin/env python3
"""wiki_visualize.py — export the wiki's hub-and-spoke graph and a linked catalog.

Emits a static Markdown site into docs/ (GitHub renders the mermaid block and the
relative links). No hosting, no builder — the artifact is the deliverable.

Usage:
    python scripts/wiki_visualize.py [--out docs] [--quiet]
    python scripts/wiki_visualize.py --check   # fail if docs/wiki-graph.md is stale (no write)
"""

import argparse
import re
import sys
from pathlib import Path

from wiki_lint import ROOT, WIKI, parse_frontmatter, rel

HUB = WIKI / "core" / "00-system-index.md"


def node_id(path: Path) -> str:
    return "N_" + re.sub(r"[^A-Za-z0-9_]", "_", path.relative_to(WIKI).as_posix())


def label(fm: dict, path: Path) -> str:
    return (fm.get("title") or fm.get("name") or path.stem).replace('"', "")


def main() -> int:
    parser = argparse.ArgumentParser(description="Wiki graph + catalog export")
    parser.add_argument("--out", default="docs")
    parser.add_argument("--quiet", action="store_true")
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the on-disk graph is stale; never write",
    )
    args = parser.parse_args()
    out_dir = Path(args.out)
    if not out_dir.is_absolute():
        out_dir = ROOT / out_dir

    docs: list[tuple[Path, dict]] = []
    for f in sorted(WIKI.rglob("*.md")):
        fm, _ = parse_frontmatter(f.read_text(encoding="utf-8"))
        if fm.get("type"):
            docs.append((f, fm))
    if not docs:
        print("no concept docs found")
        return 1

    indexes = [(f, fm) for f, fm in docs if f.stem.endswith("-index") and f != HUB]
    core = [(f, fm) for f, fm in docs if f.parent == WIKI / "core" and f != HUB]

    lines = ["```mermaid", "flowchart TD", f'  {node_id(HUB)}["System Index (hub)"]']
    edges: list[str] = []
    for f, fm in core:
        edges.append((node_id(HUB), node_id(f), label(fm, f)))
    for f, fm in indexes:
        edges.append((node_id(HUB), node_id(f), label(fm, f)))
    for a, b, lab in edges:
        lines.append(f'  {b}["{lab}"]')
        lines.append(f"  {a} --> {b}")
    lines.append("```")

    catalog = ["| Doc | Type | Description |", "|---|---|---|"]
    links: list[str] = []
    for f, fm in docs:
        href = f"../{f.relative_to(ROOT).as_posix()}"
        links.append(href)
        catalog.append(f"| [{label(fm, f)}]({href}) | {fm.get('type')} | {fm.get('description') or '—'} |")

    body = [
        "# Wiki Graph",
        "",
        "> Generated by `scripts/wiki_visualize.py` — do not edit by hand.",
        "> Regenerate: `python scripts/wiki_visualize.py`",
        "",
        "## Hub & Spoke",
        "",
        *lines,
        "",
        "## Catalog",
        "",
        *catalog,
        "",
    ]

    # Self-check: every emitted link must resolve from the output directory.
    broken = [href for href in links if not (out_dir / href).resolve().exists()]
    if broken:
        for href in broken:
            print(f"BROKEN LINK {href}")
        print(f"---\n{len(broken)} link(s) do not resolve")
        return 1

    dest = out_dir / "wiki-graph.md"
    content = "\n".join(body)
    if args.check:
        if not dest.exists():
            print(f"STALE   {rel(dest)}: missing (run: python scripts/wiki_visualize.py)")
            return 1
        if dest.read_text(encoding="utf-8") != content:
            print(f"STALE   {rel(dest)}: out of date (run: python scripts/wiki_visualize.py)")
            return 1
        if not args.quiet:
            print(f"visualizer OK: {len(docs)} docs, {len(edges)} edges - {rel(dest)} up to date")
        return 0

    out_dir.mkdir(parents=True, exist_ok=True)
    with open(dest, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)
    if not args.quiet:
        print(f"visualizer OK: {len(docs)} docs, {len(edges)} edges -> {rel(dest)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
